config/routes.rb
Rails.application.routes.draw do

  root :to => 'works#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get ":id" => "users#posts"
  get 'users/user' => "users#user"
  get 'users/ajax_user_list' => "users#ajax_user_list"
  get ':id/following' => "users#following"
  get ':id/ajax_following_list' => "users#ajax_following_list"
  get ':id/follower' => "users#follower"
  get ':id/ajax_follower_list' => "users#ajax_follower_list"
  get 'users/configuration' => "users#configuration"
  get 'users/policy' => "users#policy"
  get 'users/terms' => "users#terms"
  get 'users/contact' => "users#contact"
  get 'users/notifications' => "users#notifications"
  get 'users/ajax_validate_username' => "users#ajax_validate_username"
  get 'users/follow_request' => "users#follow_request"

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
     get :requesting, :requesters
    end
  end
  resources :follow_requests,       only: [:create, :destroy]

  post "follow_requests/:id/approval" => "follow_requests#approval"
  post "follow_requests/:id/unapproval" => "follow_requests#unapproval"

  get "post/:id" => "works#post"
  get 'works/movie' => "works#movie"
  get 'works/ajax_movie_list' => "works#ajax_movie_list"
  get 'works/book' => "works#book"
  get 'works/ajax_book_list' => "works#ajax_book_list"
  get 'works/music' => "works#music"
  get 'works/ajax_music_list' => "works#ajax_music_list"
  get 'works/new' => "works#new"
  get "works/:id/edit" => "works#edit"
  get "works/:id/copy" => "works#copy"
  post 'works/save' => "works#save"
  post "works/:id/update" => "works#update"
  post "works/:id/destroy" => "works#destroy"

  get 'memos/:post_id/new' => "memos#new"
  post "memos/create" => "memos#create"
  get 'memos/:id/edit' => "memos#edit"
  post "memos/:id/update" => "memos#update"
  post "memos/:id/destroy" => "memos#destroy"

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :invitations, only: [:create, :destroy]
  get 'invitation/:id' => "invitations#invitation"
  get 'invite' => "invitations#invite"

  get 'lists/setting/profile' => "lists#profile"
  post ":id/create_profile_sync" => "lists#create_profile_sync"
  post ":id/create_profile" => "lists#create_profile"
  post ":id/destroy_profile" => "lists#destroy_profile"
  post ":id/create_favorite" => "lists#create_favorite"
  post ":id/destroy_favorite" => "lists#destroy_favorite"

  get 'works/test' => "works#test"


  get '*path', to: 'application#render_404'
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :post, :detail]

  def test
  end

  def index  
    if user_signed_in? 
      @user  = User.find(current_user.id)
      @users = @user.followings
      @posts = Post.all
      @posts = @posts.where(user_id: @user).or(@posts.where(user_id: @users))
      @posts = @posts.order(created_at: "DESC")
      @posts = @posts.page(params[:page]).per(10)
    end
  end

  def post
    @post = Post.find(params[:id])
    @memos = Memo.where(user_id: @post.user, post_id: @post).order(created_at: "DESC")
    #画像定義
    if @post.image_url.present?
      if @post.category == "movie" || @post.category == "tv"
        @poster_show = @post.image_url.sub(/original/, 'w500')
      end
      if @post.category == "book" || @post.category == "comic"
        if @post.api == "itunes"
          @poster_show = @post.image_url.sub(/1000x1000bb/, '500x500bb')
        else
          @poster_show = @post.image_url.sub(/jpg/, 'jpg?_ex=500x500')
        end
      end
      if @post.category == "music"
        @poster_show = @post.image_url.sub(/1000x1000bb/, '500x500bb')
      end
    end
    #映画の時
    if @post.category == "movie"
      @item = Tmdb::Movie.detail(@post.work_id)
      if @item.present?
        @release = @item["release_date"].slice(0..3)
        @producer = Tmdb::Movie.director(@post.work_id)
        if @producer.present?
          @producer = @producer.first["name"]
        end
      end
    end
    #テレビの時
    if @post.category == "tv"
      @item = Tmdb::TV.detail(@post.work_id)
      if @item.present?
        @release = @item["first_air_date"].slice(0..3)
        if @item["created_by"].present?
          @producer = @item["created_by"][0]["name"]
        end
      end
    end
    #ブックの時
    if @post.category == "book"
      if @post.api == "itunes"
        @items = ITunesSearchAPI.lookup(:id => @post.work_id.to_i, :country => "jp")
        if @items.present?
          @item = @items.first
          if @item.present?
            @release = @item["releaseDate"].slice(0..3)
            @producer = @item["artistName"]
          end
        end
      else
        @items = RakutenWebService::Books::Book.search(isbn: @post.work_id.to_i)
        if @items.present?
          @item = @items.first
          if @item.present?
            @release = @item["salesDate"].slice(0..3)
            @producer = @item["author"]
          end
        end
      end
    end
    #コミックの時
    if @post.category == "comic"
      if @post.api == "itunes"
        @items = ITunesSearchAPI.lookup(:id => @post.work_id.to_i, :country => "jp")
        if @items.present?
          @item = @items.first
          if @item.present?
            @release = @item["releaseDate"].slice(0..3)
            @producer = @item["artistName"]
          end
        end
      else
        @items = RakutenWebService::Books::Book.search(isbn: @post.work_id.to_i)
        if @items.present?
          @item = @items.first
          if @item.present?
            @release = @item["salesDate"].slice(0..3)
            @producer = @item["author"]
          end
        end
      end
    end
    #ミュージックの時
    if @post.category == "music"
      @items = ITunesSearchAPI.lookup(:id => @post.work_id.to_i, :country => "jp")
      if @items.present?
        @item = @items.first
        if @item.present?
          @release = @item["releaseDate"].slice(0..3)
          @producer = @item["artistName"]
        end
      end
    end
  end

  def movie
  	@defaults = Tmdb::Movie.popular
  	@defaults = @defaults[:results]
  end

  def ajax_movie_list
    if params[:q].present?
      @items = Tmdb::Search.multi(params[:q])
      @items = @items[:results]
    else
      @defaults = Tmdb::Movie.popular
      @defaults = @defaults[:results]
    end
  end

  def book
  	@defaults = ITunesSearchAPI.search(:term => "comic", :country => "jp", :media => "ebook", :limit  => '30')
  end

  def ajax_book_list
    if params[:q].present?
      @items_itunes = ITunesSearchAPI.search(:term => params[:q], :country => "jp", :media => "ebook", :limit  => '30')
      if @items_itunes.present?
        if @items_itunes.size <= 10
          @items_rakuten = RakutenWebService::Books::Book.search(title: params[:q], hits: 30)
        end
      else
        @items_rakuten = RakutenWebService::Books::Book.search(title: params[:q], hits: 30)
      end
    else
      @defaults = ITunesSearchAPI.search(:term => "comic", :country => "jp", :media => "ebook", :limit  => '30')
    end
  end

  def music
  	@defaults = ITunesSearchAPI.search(:term => "jpop", :country => "jp", :media => "music",:entity =>'song', :limit  => '30', :attribute => "mixTerm")
  end

  def ajax_music_list
    if params[:q].present?
      @items = ITunesSearchAPI.search(:term => params[:q], :country => "jp", :media => "music",:entity =>'song', :limit  => '30')
    else
      @defaults = ITunesSearchAPI.search(:term => "jpop", :country => "jp", :media => "music",:entity =>'song', :limit  => '30', :attribute => "mixTerm")
    end
  end

  def new
    if params[:category] == "movie" || params[:category] == "tv"
      if params[:category] == "movie"
        @item = Tmdb::Movie.detail(params[:id].to_i)
        @title = @item["title"]
        @work_id = @item["id"]
        @category = params[:category]
        @poster = "https://image.tmdb.org/t/p/original" + @item["poster_path"].to_s
        @poster_ja = Tmdb::Movie.posters(@item["id"], language: 'ja')
        @poster_ja = @poster_ja.sort_by! { |a| -a[:vote_average] }.first(2)
        @poster_en = Tmdb::Movie.posters(@item["id"], language: 'en')
        @poster_en = @poster_en.sort_by! { |a| -a[:vote_average] }.first(6)
        @posters = @poster_ja + @poster_en
     end
      if params[:category] == "tv"
        @item = Tmdb::TV.detail(params[:id].to_i)
        @title = @item["name"]
        @work_id = @item["id"]
        @category = params[:category]
        @poster = "https://image.tmdb.org/t/p/original" + @item["poster_path"].to_s
        @poster_ja = Tmdb::TV.posters(@item["id"], language: 'ja')
        @poster_ja = @poster_ja.sort_by! { |a| -a[:vote_average] }.first(2)
        @poster_en = Tmdb::TV.posters(@item["id"], language: 'en')
        @poster_en = @poster_en.sort_by! { |a| -a[:vote_average] }.first(6)
        @posters = @poster_ja + @poster_en
      end
    end
    if params[:category] == "book" || params[:category] == "comic"
      if params[:api] == "rakuten"
        @items = RakutenWebService::Books::Book.search(isbn: params[:id].to_i)
        if @items.present?
          @item = @items.first
        end
        @title = @item["title"]
        @work_id = params[:id].to_i
        @category = params[:category]
        @poster = @item["largeImageUrl"]
        @poster = @poster.sub!(/_ex.*/m, "")
        @poster = @poster.chop!
        @api = "rakuten"
      end
      if params[:api] == "itunes"
        @items = ITunesSearchAPI.lookup(:id => params[:id].to_i, :country => "jp")
        if @items.present?
          @item = @items.first
        end
        @title = @item["trackCensoredName"]
        @work_id = params[:id].to_i
        @category = params[:category]
        @poster = @item["artworkUrl100"]
        @poster = @poster.sub(/100x100bb/, '1000x1000bb')
        @api = "itunes"
      end
    end
    if params[:category] == "music"
      @items = ITunesSearchAPI.lookup(:id => params[:id].to_i, :country => "jp")
      if @items.present?
        @item = @items.first
      end
      @title = @item["trackCensoredName"]
      @work_id = @item["trackId"]
      @category = params[:category]
      @poster = @item["artworkUrl100"]
      @poster = @poster.sub(/100x100bb/, '1000x1000bb')
      @preview_url = @item["previewUrl"]
    end
    #画像定義
    if @poster.present?
      if @category == "movie" || @category == "tv"
        @poster_show = @poster.sub(/original/, 'w500')
      end
      if @category == "book" || @category == "comic"
        if @api == "itunes"
          @poster_show = @poster.sub(/1000x1000bb/, '500x500bb')
        else
          @poster_show = @poster.sub(/jpg/, 'jpg?_ex=500x500')
        end
      end
      if @category == "music"
        @poster_show = @poster.sub(/1000x1000bb/, '500x500bb')
      end
    end
  end

  def save
  	if params[:category] == "movie" || params[:category] == "tv"
  		@post = Post.new(user_id: current_user.id, title: params[:title], description: params[:description], category: params[:category], image_url: params[:image_url], review: params[:review], work_id: params[:work_id])
  	end
  	if params[:category] == "book" || params[:category] == "comic"
  		@post = Post.new(user_id: current_user.id, title: params[:title], description: params[:description], category: params[:category], image_url: params[:image_url], review: params[:review], work_id: params[:work_id], api: params[:api])
  	end
  	if params[:category] == "music"
  		@post = Post.new(user_id: current_user.id, title: params[:title], description: params[:description], category: params[:category], image_url: params[:image_url], review: params[:review], work_id: params[:work_id], preview_url: params[:preview_url])
  	end
  	if @post.save
      redirect_to root_path
    else
      redirect_to root_path
    end     
  end

  def edit
  	@post = Post.find(params[:id])
    if !(current_user == @post.user)
      redirect_to root_path
    end
    if @post.category == "movie"
  		@item = Tmdb::Movie.detail(@post.work_id)
	  	@poster_ja = Tmdb::Movie.posters(@post.work_id, language: 'ja')
	  	@poster_ja = @poster_ja.sort_by! { |a| -a[:vote_average] }.first(2)
	    @poster_en = Tmdb::Movie.posters(@post.work_id, language: 'en')
	    @poster_en = @poster_en.sort_by! { |a| -a[:vote_average] }.first(6)
	    @posters = @poster_ja + @poster_en
	  end
	  if @post.category == "tv"
  		@item = Tmdb::TV.detail(@post.work_id)
	  	@poster_ja = Tmdb::TV.posters(@post.work_id, language: 'ja')

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_book_list.html.erb
<% if params[:q].present? %>
  <%#itunesの検索結果%>
  <% if @items_itunes.present? %>
    <% @items_itunes.each.with_index(1) do |item, i| %>
      <%= form_tag(works_new_path, method: :get) do %>
        <% if item["genres"].include?("マンガ") %>
          <%= hidden_field_tag :category, "comic" %>
        <% else %>
          <%= hidden_field_tag :category, "book" %>
        <% end %>
        <%= hidden_field_tag :id, item["trackId"] %>
        <%= hidden_field_tag :api, "itunes" %>
        <button type="submit" style="width:100%;">
          <div style="text-align:left;margin:0 10px;padding:12px 5px;border-bottom:solid 0.5px rgba(150, 150, 150, 0.2);">
            <div class="inline_block_middle" style="width:18%;">
              <% if item["artworkUrl100"].blank? %>
                <img data-src="/assets/book.jpg" class="img_tavore lazyload">
              <% else %>
                <% @image_url = item["artworkUrl100"] %>
                <% @image_url = @image_url.sub(/100x100bb/, '200x200bb') %>
                <img data-src="<%= @image_url %>" class="img_tavore lazyload">
              <% end %>
            </div>
            <div class="inline_block_middle" style="width:77%;padding:0px 20px;">
              <div class="line_limit02">
                <div style="font-size:14px;color:#FAFAFA;font-weight:bolder;margin-top:2px;">
                  <%= item["trackCensoredName"] %>  
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  <%= item["artistName"] %>
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  Ebook
                </div>
              </div>
            </div>
            <div class="inline_block_middle" style="width:5%;">
              <% if Post.find_by(user_id: current_user.id, work_id: item["trackId"]).present? %>
                <img data-src="/assets/checked_2FB4B4.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% else %>
                <img data-src="/assets/right_FAFAFA.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% end %>
            </div>
          </div>
        </button>
      <% end %>
    <% end %>
  <% end %>
  <%#楽天の検索結果%>
  <% if @items_rakuten.present? %>
    <% @items_rakuten.each do |item| %>
      <%= form_tag(works_new_path, method: :get) do %>
        <% if item["size"] == "コミック" %>
          <%= hidden_field_tag :category, "comic" %>
        <% else %>
          <%= hidden_field_tag :category, "book" %>
        <% end %>
        <%= hidden_field_tag :id, item["isbn"] %>
        <%= hidden_field_tag :api, "rakuten" %>
        <button type="submit" style="width:100%;">
          <div style="text-align:left;margin:0 10px;padding:12px 5px;border-bottom:solid 0.5px rgba(150, 150, 150, 0.2);">
            <div class="inline_block_middle" style="width:18%;">
              <% if item["largeImageUrl"].blank? %>
                <img data-src="/assets/book.jpg" class="img_tavore lazyload">
              <% else %>
                <% @image_url = item["largeImageUrl"] %>
                <img data-src="<%= @image_url %>" class="img_tavore lazyload">
              <% end %>
            </div>
            <div class="inline_block_middle" style="width:77%;padding:0px 20px;">
              <div class="line_limit02">
                <div style="font-size:14px;color:#FAFAFA;font-weight:bolder;margin-top:2px;">
                  <%= item["title"] %> 
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  <%= item["author"] %>
                </div>
              </div>
            </div>
            <div class="inline_block_middle" style="width:5%;">
              <% if Post.find_by(user_id: current_user.id, work_id: item["isbn"]).present? %>
                <img data-src="/assets/checked_2FB4B4.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% else %>
                <img data-src="/assets/right_FAFAFA.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% end %>
            </div>
          </div>
        </button>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%#itunesでのdefault%>
  <% if @defaults.present? %>
    <% @defaults.each.with_index(1) do |item, i| %>
      <%= form_tag(works_new_path, method: :get) do %>
        <% if item["genres"].include?("マンガ") %>
          <%= hidden_field_tag :category, "comic" %>
        <% else %>
          <%= hidden_field_tag :category, "book" %>
        <% end %>
        <%= hidden_field_tag :id, item["trackId"] %>
        <%= hidden_field_tag :api, "itunes" %>
        <button type="submit" style="width:100%;">
          <div style="text-align:left;margin:0 10px;padding:12px 5px;border-bottom:solid 0.5px rgba(150, 150, 150, 0.2);">
            <div class="inline_block_middle" style="width:18%;">
              <% if item["artworkUrl100"].blank? %>
                <img data-src="/assets/book.jpg" class="img_tavore lazyload">
              <% else %>
                <% @image_url = item["artworkUrl100"] %>
                <% @image_url = @image_url.sub(/100x100bb/, '200x200bb') %>
                <img data-src="<%= @image_url %>" class="img_tavore lazyload">
              <% end %>
            </div>
            <div class="inline_block_middle" style="width:77%;padding:0px 20px;">
              <div class="line_limit02">
                <div style="font-size:14px;color:#FAFAFA;font-weight:bolder;margin-top:2px;">
                  <%= item["trackCensoredName"] %>  
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  <%= item["artistName"] %>
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  Ebook
                </div>
              </div>
            </div>
            <div class="inline_block_middle" style="width:5%;">
              <% if Post.find_by(user_id: current_user.id, work_id: item["trackId"]).present? %>
                <img data-src="/assets/checked_2FB4B4.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% else %>
                <img data-src="/assets/right_FAFAFA.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% end %>
            </div>
          </div>
        </button>
      <% end %>
    <% end %>
  <% end %>
 <% end %>

<%#lazyload.js%>
<script defer>
  $(function() {
    $('img.lazyload').lazyload();
  });
</script>

app/views/works/_home.html.erb
<%= video_tag("TAVORE.mp4",:muted => true, :autoplay => true, :loop => true, :playsinline => true) %>

<div class="base_home">
	<span>
		<div class="tango01">
			<div style="text-align:center;">
				<div class="font_logo">
					TAVORE
				</div>
				<div class="font_logo_sub01">									
					読む、観る、聴く。					
				</div>
				<div class="height_logo"></div>
				<% if user_signed_in? %>
					<div style="display:inline-block;margin:0px 10px;">
						<%= link_to "/works/index" do %>
				          <div class="btn_register">
							フィードへ
						  </div>
				        <% end %>
					</div>
				<% else %>
					<div style="display:inline-block;margin:0px 10px;">
						<a href="" data-toggle="modal" data-target="#myModal_sign_in">
				          <div class="btn_session">
							ログイン
						  </div>
				        </a>
					</div>
					<div style="display:inline-block;margin:0px 10px;">
						<a href="" data-toggle="modal" data-target="#myModal_sign_up">
					        <div class="btn_register">
								アカウント作成
							</div>
				        </a>
					</div>
				<% end %>
			</div>
		</div>
	</span>
</div>

<div class="modal fade" id="myModal_sign_in">
	<div class="height_modal"></div>
    <div class="modal-dialog">
    	<div class="base02">
			<span>
				<div class="layer12">
				</div>
				<div class="layer11">
				</div>
				<div class="layer06">
					<div class="font_white_big">
						Sign in
					</div>
					<div class="gogo">
						<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
						  <%= f.email_field :email,placeholder: "email", required: "", autofocus: true %>
						  <%= f.password_field :password,placeholder: "password", required: "" %>
						  <div style="height:3vh;"></div>
	          			  <%= f.submit "完了",class:"btn_session" %>
						<% end %>
						<div style="height:5vh;"></div>
					</div>
				</div>
				<div class="layer04">
					<div class="pro17">
						<div style="margin:0px 0px 20px 20px;">
							<a href="" data-toggle="modal" data-dismiss="modal">
								<%= image_tag "left_gray.png", :class =>'img_left' %>
							</a>
						</div>
					</div>
					<div class="pro17" style="text-align:right;">
						<%= link_to new_user_password_path do %>
							<div class="font_gray_min" style="margin:0px 20px 20px 0px;">
								パスワードを忘れたら
							</div>
						<% end %>
					</div>
				</div>
			</span>
		</div>
    </div>
</div>

<div class="modal fade" id="myModal_sign_up">
	<div class="height_modal"></div>
    <div class="modal-dialog">
    	<div class="base02">
			<span>
				<div class="layer12">
				</div>
				<div class="layer11">
				</div>
				<div class="layer06">
					<div class="font_white_big">
						Sign up
					</div>
					<div class="gogo">
						<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
						  <%= f.text_field :name,placeholder: "name", required: "", autofocus: true %>
						  <%= f.email_field :email,placeholder: "email", required: "" %>
						  <%= f.password_field :password,placeholder: "password", required: "" %>
						  <%= f.password_field :password_confirmation,:placeholder => 'password confirmation', required: "" %>
						  <div style="height:2vh;"></div>
	          			  <%= f.submit "完了",class:"btn_session" %>
						<% end %>
					</div>
					<div style="height:5vh;"></div>
				</div>
				<div class="layer04">
					<div class="pro17">
						<div style="margin:0px 0px 20px 20px;">
							<a href="" data-toggle="modal" data-dismiss="modal">
								<%= image_tag "left_gray.png", :class =>'img_left' %>
							</a>
						</div>
					</div>
				</div>
			</span>
		</div>
    </div>
</div>

app/views/works/_movie_list.html.erb
<% if params[:q].present? %>
  <%#検索結果%>
  <% if @items.present? %>
    <% @items.each do |item| %>
      <% if item["media_type"] == "movie" || item["media_type"] == "tv" %>
        <%= form_tag(works_new_path, method: :get) do %>
        <%= hidden_field_tag :category, item["media_type"] %>
        <%= hidden_field_tag :id, item["id"] %>
          <button type="submit" style="width:100%;">
            <div style="text-align:left;margin:0 10px;padding:12px 5px;border-bottom:solid 0.5px rgba(150, 150, 150, 0.2);">
              <div class="inline_block_middle" style="width:18%;">
                <% if item["poster_path"].blank? %>
                  <img data-src="/assets/movie.jpg" class="img_tavore lazyload">
                <% else %>
                  <img data-src="https://image.tmdb.org/t/p/w154/<%= item.poster_path %>" class="img_tavore lazyload">
                <% end %>
              </div>
              <div class="inline_block_middle" style="width:77%;padding:0px 20px;">
                <div class="line_limit02">
                  <div style="font-size:14px;color:#FAFAFA;font-weight:bolder;margin-top:2px;">
                    <% if item["media_type"] == "movie" %>
                      <%= item["title"] %>
                    <% end %> 
                    <% if item["media_type"] == "tv" %>
                      <%= item["name"] %>
                    <% end %>   
                  </div>
                </div>
                <div class="line_limit01">
                  <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                    <% if item["media_type"] == "movie" %>
                      <%= item["release_date"].slice(0..3) %>
                    <% end %> 
                    <% if item["media_type"] == "tv" %>
                      <%= item["first_air_date"].slice(0..3) %>
                    <% end %>  
                  </div>
                </div>
              </div>
              <div class="inline_block_middle" style="width:5%;">
                <% if Post.find_by(user_id: current_user.id, work_id: item["id"]).present? %>
                  <img data-src="/assets/checked_2FB4B4.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
                <% else %>
                  <img data-src="/assets/right_FAFAFA.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
                <% end %>
              </div>
            </div>
          </button>
        <% end %>
      <% end %> 
    <% end %>
  <% end %>
<% else %>
  <%#default%>
  <% if @defaults.present? %>
    <% @defaults.each do |item| %>
      <%= form_tag(works_new_path, method: :get) do %>
        <%= hidden_field_tag :category, "movie" %>
        <%= hidden_field_tag :id, item["id"] %>
        <button type="submit" style="width:100%;">
          <div style="text-align:left;margin:0 10px;padding:12px 5px;border-bottom:solid 0.5px rgba(150, 150, 150, 0.2);">
            <div class="inline_block_middle" style="width:18%;">
              <% if item["poster_path"].blank? %>
                <img data-src="/assets/movie.jpg" class="img_tavore lazyload">
              <% else %>
                <img data-src="https://image.tmdb.org/t/p/w154/<%= item.poster_path %>" class="img_tavore lazyload">
              <% end %>
            </div>
            <div class="inline_block_middle" style="width:77%;padding:0px 20px;">
              <div class="line_limit02">
                <div style="font-size:14px;color:#FAFAFA;font-weight:bolder;margin-top:2px;">
                  <%= item["title"] %>  
                </div>
              </div>
              <div class="line_limit01">
                <div style="font-size:12px;color:#FAFAFA;opacity:0.8;">
                  <%= item["release_date"].slice(0..3) %>            
                </div>
              </div>         
            </div>
            <div class="inline_block_middle" style="width:5%;">
              <% if Post.find_by(user_id: current_user.id, work_id: item["id"]).present? %>
                <img data-src="/assets/checked_2FB4B4.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% else %>
                <img data-src="/assets/right_FAFAFA.svg" class="lazyload" style="width:15px;height:15px;opacity:0.8;">
              <% end %>
            </div>
          </div>
        </button>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%#lazyload.js%>
<script defer>
  $(function() {
    $('img.lazyload').lazyload();
  });
</script>

app/views/works/ajax_book_list.js.erb
$("#book_list").html("<%= escape_javascript(render 'book_list', items: @items) %>");

app/views/works/ajax_movie_list.js.erb
$("#movie_list").html("<%= escape_javascript(render 'movie_list', items: @items) %>");

app/views/works/ajax_music_list.js.erb
$("#music_list").html("<%= escape_javascript(render 'music_list', items: @items) %>");