config/routes.rb
Rails.application.routes.draw do

  root :to => 'works#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get ":id" => "users#posts"
  get 'users/user' => "users#user"
  get 'users/ajax_user_list' => "users#ajax_user_list"
  get ':id/following' => "users#following"
  get ':id/ajax_following_list' => "users#ajax_following_list"
  get ':id/follower' => "users#follower"
  get ':id/ajax_follower_list' => "users#ajax_follower_list"
  get 'users/configuration' => "users#configuration"
  get 'users/policy' => "users#policy"
  get 'users/terms' => "users#terms"
  get 'users/contact' => "users#contact"
  get 'users/notifications' => "users#notifications"
  get 'users/ajax_validate_username' => "users#ajax_validate_username"
  get 'users/follow_request' => "users#follow_request"

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
     get :requesting, :requesters
    end
  end
  resources :follow_requests,       only: [:create, :destroy]

  post "follow_requests/:id/approval" => "follow_requests#approval"
  post "follow_requests/:id/unapproval" => "follow_requests#unapproval"

  get "post/:id" => "works#post"
  get 'works/movie' => "works#movie"
  get 'works/ajax_movie_list' => "works#ajax_movie_list"
  get 'works/book' => "works#book"
  get 'works/ajax_book_list' => "works#ajax_book_list"
  get 'works/music' => "works#music"
  get 'works/ajax_music_list' => "works#ajax_music_list"
  get 'works/new' => "works#new"
  get "works/:id/edit" => "works#edit"
  get "works/:id/copy" => "works#copy"
  post 'works/save' => "works#save"
  post "works/:id/update" => "works#update"
  post "works/:id/destroy" => "works#destroy"

  get 'memos/:post_id/new' => "memos#new"
  post "memos/create" => "memos#create"
  get 'memos/:id/edit' => "memos#edit"
  post "memos/:id/update" => "memos#update"
  post "memos/:id/destroy" => "memos#destroy"

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :invitations, only: [:create, :destroy]
  get 'invitation/:id' => "invitations#invitation"
  get 'invite' => "invitations#invite"

  get 'lists/setting/profile' => "lists#profile"
  post ":id/create_profile_sync" => "lists#create_profile_sync"
  post ":id/create_profile" => "lists#create_profile"
  post ":id/destroy_profile" => "lists#destroy_profile"
  post ":id/create_favorite" => "lists#create_favorite"
  post ":id/destroy_favorite" => "lists#destroy_favorite"

  get 'works/test' => "works#test"


  get '*path', to: 'application#render_404'
end

app/views/partial/_dashbord.html.erb
<div class="modal fade" id="myModal_dashbord">
  <div class="modal-dialog">
    <div class="a1">
      <div class="a4">
        <div class="d1">
          <div class="d7"></div>
          <% if @list = List.find_by(user_id: current_user.id, title: "プロフィール") %>
              <% if @list_item = ListItem.find_by(list_id: @list.id) %>
                <img data-src="<%= @list_item.post.image_url %>" class="img_myboom lazyload_modal_dashbord %>">
              <% else %>
                <%#myboomのデフォルト画像%>
              <% end %>
            <% else %>
              <%#myboomのデフォルト画像%>
            <% end %>
        </div>
      </div>
      <div class="a11">
        <div class="font_white" style="margin:10px;width:35%;display:inline-block;">
          <div class="contain_title02">
            <% if @list_item.present? %>
              <div>
                <% if @list_item.post.category == "movie" %>
                  <%= image_tag "movie_white.png", :class =>'icon_category' %> <%= @list_item.post.title %>
                <% end %>
                <% if @list_item.post.category == "tv" %>
                  <%= image_tag "movie_white.png", :class =>'icon_category' %> <%= @list_item.post.title %>
                <% end %>
                <% if @list_item.post.category == "book" %>
                  <%= image_tag "book_white.png", :class =>'icon_category' %> <%= @list_item.post.title %>
                <% end %>
                <% if @list_item.post.category == "comic" %>
                  <%= image_tag "book_white.png", :class =>'icon_category' %> <%= @list_item.post.title %>
                <% end %>
                <% if @list_item.post.category == "music" %>
                  <%= image_tag "music_white.png", :class =>'icon_category' %> <%= @list_item.post.title %>
                <% end %>
              </div>
            <% else %>
              <div>
                <%#myboomが設定されていません%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="a8">    
        <div style="width:100%;"> 
          <div class="pro34" style="vertical-align:bottom;">
            <%= link_to "/users/following" do %>              
              <div style="font-size:11px;color:#C2C2C2;border-bottom: solid 1px rgba(5,98,123,0.8);margin-bottom:1vh;">
                  <%= current_user.followings.size %> followings
              </div> 
            <% end %>
          </div>       
          <div class="pro33" style="vertical-align:bottom;">
            <div style="text-align:center;">
              <% if current_user.image.present? %>
                <img data-src="<%= current_user.image(:large) %>" class="img_user08 lazyload_modal_dashbord">
              <% else %>
                <%= image_tag "user09.png", :class =>'img_user08' %>
              <% end %>
            </div>
            <div style="font-size:18px;text-align:center;margin-top:10px;">
              <%= current_user.name %>
              <% if current_user.authority == "public" %>
                <%= image_tag "test55.png", :style =>'width:14px;height:14px;' %>
              <% end %>
            </div>
          </div>
          <div class="pro34" style="vertical-align:bottom;">
            <%= link_to "/users/follower" do %>   
              <div style="font-size:11px;color:#C2C2C2;border-bottom: solid 1px rgba(5,98,123,0.8);margin-bottom:1vh;">
                  <%= current_user.followers.size %> followers
              </div> 
            <% end %>
          </div>           
        </div>   
        <% if current_user.description.present? %>
          <div style="height:0.5vh;"></div>
          <div class="font_gray_min" style="width:50%;color:#C2C2C2;display:inline-block;">
            <%= simple_format(current_user.description, {}, wrapper_tag: "div") %>
          </div>
        <% else %>
          <div style="height:1vh;"></div>
          <%= link_to edit_user_registration_path do %>
            <div class="font_gray_min" style="width:50%;color:#2FB4B4;display:inline-block;">
              自己紹介を書く
            </div>
          <% end %>
        <% end %>
        <div style="height:4vh;"></div>
        <div style="text-align:center;">
          <%= link_to "/#{current_user.username}/posts", :style => "display:inline-block;vertical-align:top;margin:0 5px;" do %>
            <div class="btn_follow_on">
              <%= image_tag "bag_white.png", :style =>'width:16px;height:16px;margin-top:-3.5px;' %>&nbsp;&nbsp;投稿へ
            </div>
          <% end %>
          <div style="display:inline-block;vertical-align:top;">
            <%= link_to configuration_path do %>
              <div class="btn_follow_on" style="padding-left:1.0em;padding-right:1.0em;">
                <%= image_tag "control_white.png", :style =>'width:14px;height:14px;margin-top:-2px' %>        
              </div>
            <% end %>
          </div>
        </div>    
        <div style="height:8vh;"></div>  
        <div style="text-align:center;width:95%;display:inline-block;">
          <div class="pro20">
            <div>
              <%= image_tag "checked_white.png", :style =>'width:16px;height:16px;' %>
            </div> 
            <div style="font-size:12px;margin-top:5px;">
              <%= Post.where(user_id: current_user.id).where.not(review: "bookmark").size %> checkeds
            </div> 
          </div>
          <div class="pro20">
            <div>
              <%= image_tag "bookmark_white.png", :style =>'width:16px;height:16px;' %>
            </div> 
            <div style="font-size:12px;margin-top:5px;">
              <%= Post.where(user_id: current_user.id, review: "bookmark").size %> bookmarks
            </div> 
          </div>
          <div class="pro20">
            <div>
              <%= image_tag "file_white.png", :style =>'width:16px;height:16px;' %>
            </div> 
            <div style="font-size:12px;margin-top:5px;">
              coming soon
            </div> 
          </div>
        </div>  
        <div style="height:10vh;"></div>
      </div>
      <div class="a10">
        <div class="pro19">             
          <a data-dismiss="modal" id="dismiss_dashbord">
            <%= image_tag "close_blue.png", :class =>'img_left02' %>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<%#lazyload.js%>
<script type="text/javascript">
  $('#myModal_dashbord').on("show.bs.modal", function () {
      $('img.lazyload_modal_dashbord').lazyload();
    });      
</script>

<%#モーダルtubolinks不具合修正%>
<script type="text/javascript">
  $(function(){
    var display_dashbord = $('#myModal_dashbord').css('display');
    //モーダルが表示されているのに表示判定されてなかったら
    if(display_dashbord === 'block'){
      //モーダルを表示状態にする        
      $('body').removeClass('modal-open');
      $('.modal-backdrop').remove();
      $('#myModal_dashbord').modal('toggle');
      //クリックでモーダルを閉じる 
      $('#dismiss_dashbord').on("click",function(){
        $('body').removeClass('modal-open');
          $('.modal-backdrop').remove();
        $('#myModal_dashbord').modal('hide'); 
      });
    }       
  });
</script>

app/views/partial/_home.html.erb
<%#ファーストビュー%>
<div class="a1" style="height:calc(100% - 0px);">
    <div class="a8" style="text-align:center;">
      	<%= image_tag "tavore_logo_01.png", :style =>'width:110px;height:110px;' %>
      	<div style="font-size:20px;margin-top:-5px;letter-spacing:0.05em;">
        	TAVORE
      	</div>
      	<div style="height:5px;"></div>
      	<div style="font-size:12px;opacity:0.8;letter-spacing:0.02em;">
      		log of movie, book, music
      	</div>
      	<div style="height:30px;"></div>
      	<div style="width:80%;display:inline-block;">
			<div class="inline_block_middle" style="text-align:center;width:48%;">
				<%= link_to new_user_session_path do %>
			    	<div style="width:100%;padding:0.7em 0em;color:rgba(250,250,250,1);background:rgba(40,40,40,0.5);border:solid 1px rgba(40,40,40,0.1);border-radius:2px;font-size:14px;letter-spacing:0.05em;display:inline-block;vertical-align:middle;text-align:center;box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);">
						ログイン
					</div>
			    <% end %>
		    </div>
		    <div class="inline_block_middle" style="text-align:center;width:4%;">
		    </div>
		    <div class="inline_block_middle" style="text-align:center;width:48%;">
		    	<%= link_to new_user_registration_path do %>
			    	<div style="width:100%;padding:0.7em 0em;color:rgba(250,250,250,1);background:rgba(5,98,123,0.5);border:solid 1px rgba(5,98,123,0.1);border-radius:2px;font-size:14px;letter-spacing:0.05em;display:inline-block;vertical-align:middle;text-align:center;box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);">
						アカウント作成
					</div>
			    <% end %>
		    </div>					   
		</div>
		<div style="height:80px;"></div>
    </div>
</div>

app/views/partial/_modal_half.html.erb
<div class="modal bottom fade" id="myModal_half_<%= post.id %>">
	<div class="modal-dialog">
		<div class="a1">
          	<div class="a4">
            	<div class="d1">
              		<div class="d2" style="background:rgba(15,15,15,1);"></div>
            	</div>
          	</div>
          	<div class="a6" style="text-align:center;">
          		<div style="position:relative;width:0;height:0;z-index:1;"></div>
          		<div style="width:100%;height:100%;overflow-y:scroll;-webkit-overflow-scrolling:touch;"> 
          			<div style="min-height:101%;"> 
		          		<div style="height:30px;"></div>
		          		<div style="width:45%;display:inline-block;">
		          			<% if post.image_url.blank? %>
								<img data-src="/assets/<%= post.category %>.jpg" class="lazyload_half_modal_<%= post.id %>" style="width:100%;height:auto;border-radius:5px;">
							<% else %>	
								<% if post.category == "movie" || post.category == "tv" %>
									<% @poster_show = post.image_url.sub(/original/, 'w500') %>
								<% end %>
								<% if post.category == "book" || post.category == "comic" %>
									<% if post.api == "itunes" %>
										<% @poster_show = post.image_url.sub(/1000x1000bb/, '500x500bb') %>
									<% else %>
										<% @poster_show = post.image_url.sub(/jpg/, 'jpg?_ex=500x500') %>
									<% end %>
								<% end %>
								<% if post.category == "music" %>
									<% @poster_show = post.image_url.sub(/1000x1000bb/, '500x500bb') %>
								<% end %>
								<img data-src="<%= @poster_show %>" class="lazyload_half_modal_<%= post.id %>" style="width:100%;height:auto;border-radius:5px;">
							<% end %>
		          		</div>
		          		<div style="height:10px;"></div>
		          		<div class="font_white_big" style="width:90%;display:inline-block;font-weight:bold;">
		          			<%= post.title %>
		          		</div>
		          		<div style="height:30px;"></div>
		          		<div style="width:100%;padding:0 12%;">
		          			<%#本人だったら%>
		          			<% if user_signed_in? %>	          				
				          		<% if post.user.id == current_user.id %>			          			
									<span id="favorite-of-<%= post.id %>">
								      	<%= render partial: 'lists/favorite', locals: { post: post } %>
								    </span>	
								    <div style="height:30px"></div>					    	
									<%= link_to "/works/#{post.id}/edit" do %>
										<div class="btn_half_item">  
											<%= image_tag "edit_FAFAFA.svg", :style =>'width:18px;height:18px;margin-right:15px;' %>投稿を編集
										</div>
									<% end %>
									<div style="height:30px"></div>			
									<%= link_to "/works/#{post.id}/destroy", method: :post, data: { confirm: '削除しますか？' } do %>
										<div class="btn_half_item" style="color:#FB473E;">  
											<%= image_tag "trash_FB473E.svg", :style =>'width:18px;height:18px;margin-right:15px;' %>投稿を削除
										</div>
									<% end %>
									<div style="height:30px"></div>
								<% end %>
							<% end %>
							<a href="http://twitter.com/share?url=<%= root_url(only_path: false) %>post/<%= post.id %>" target="_blank">
								<div class="btn_half_item">  						
									<%= image_tag "twitter.svg", :style =>'width:22px;height:22px;margin-right:15px;border-radius:50%;' %>Twitterでシェア
								</div>
							</a>
							<div style="height:30px"></div>
							<a href="https://www.facebook.com/sharer/sharer.php?u=<%= root_url(only_path: false) %>post/<%= post.id %>" target="_blank">
								<div class="btn_half_item">  						
									<%= image_tag "facebook.svg", :style =>'width:22px;height:22px;margin-right:15px;border-radius:50%;' %>Facebookでシェア
								</div>
							</a>
							<div style="height:30px"></div>
		          			<a href="http://line.me/R/msg/text/?<%= root_url(only_path: false) %>post/<%= post.id %>" target="_blank">
								<div class="btn_half_item">  
									<%= image_tag "line.svg", :style =>'width:22px;height:22px;margin-right:15px;border-radius:50%;' %>LINEでシェア
								</div>
							</a>
							<div style="height:30px"></div>
		          			<span data-clipboard-text="<%= root_url(only_path: false) %>post/<%= post.id %>" id="copy_<%= post.id %>">
								<div class="btn_half_item">  
									<%= image_tag "link_FAFAFA.svg", :style =>'width:16px;height:16px;margin-right:15px;margin-left:5px;' %>リンクをコピー
								</div>
							</span>	
							<div style="height:90px"></div>	
						</div>
					</div>
				</div>
          	</div>
          	<div class="a13" style="text-align:center;">
          		<span data-toggle="modal" data-dismiss="modal" id="dismiss_myModal_half_<%= post.id %>">
					<div class="btn_half_close">  
						<%= image_tag "ban_FAFAFA.svg", :style =>'width:20px;height:20px;margin-top:-2px;margin-right:5px;' %>キャンセル
					</div>
			  	</span>
          	</div>
        </div>
	</div>
</div>

<%#モーダルlazyload%>
<script defer>
	$('#myModal_half_<%= post.id %>').on("show.bs.modal", function () {
    	$('img.lazyload_half_modal_<%= post.id %>').lazyload();
    });      
</script>
<%#モーダルtubolinks不具合修正%>
<script defer>
	$(function(){
		var display_<%= post.id %> = $('#myModal_half_<%= post.id %>').css('display');
		//モーダルが表示されているのに表示判定されてなかったら
		if(display_<%= post.id %> === 'block'){
			//モーダルを表示状態にする
			$('body').removeClass('modal-open');
				$('.modal-backdrop').remove();				
			$('#myModal_half_<%= post.id %>').modal('toggle');
			//クリックでモーダルを閉じる 
			$('#dismiss_myModal_half_<%= post.id %>').on("click",function(){
				$('body').removeClass('modal-open');
			  	$('.modal-backdrop').remove();
				$('#myModal_half_<%= post.id %>').modal('hide'); 
			});
		}				
	});
</script>
<%#クリップボード%>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.8/clipboard.min.js"></script>
<%#コピーのJS%>
<script defer>
	$(function(){
	  var clipboard = new Clipboard('#copy_<%= post.id %>');
	  clipboard.on('success', function(e) {
	    console.info('Trigger:', e.trigger);
	    alert('コピーできました');
	  });
	  clipboard.on('error', function(e) {
	    console.error('Trigger:', e.trigger);
	    alert('このブラウザでは対応していません');
	  });
  	});
</script>	  

app/views/partial/_modal_post.html.erb
<%#投稿ボタン%>
<div style="position:fixed;bottom:3%;left:0%;width:76%;margin:0 12%;z-index:99;">
	<div style="width:33.3333%;display:inline-block;text-align:left;padding-left:15px;">
		<% if request.path == "/" %>
			<span onclick="scrollGO()" style="position:relative;display:inline-block;vertical-align:middle;width:50px;height:50px;line-height:50px;background:rgba(25,25,25,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
				<i>
					<%= image_tag "up_FAFAFA.svg", :style =>'width:16px;height:16px;opacity:0.8;' %>
				</i>
			</span>
		<% else %>
			<a href="/" style="position:relative;display:inline-block;vertical-align:middle;width:50px;height:50px;line-height:50px;background:rgba(25,25,25,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
				<i>
					<%= image_tag "home_FAFAFA.svg", :style =>'width:16px;height:16px;opacity:0.8;' %>
				</i>
			</a>
		<% end %>
	</div>
	<div style="width:33.3333%;display:inline-block;text-align:center;">
		<a href="#" data-toggle="modal" data-target="#myModal_post" style="position:relative;display:inline-block;vertical-align:middle;width:60px;height:60px;line-height:60px;background:rgba(0,60,85,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
			<i>
				<%= image_tag "plus_FAFAFA.svg", :style =>'width:22px;height:22px;' %>
			</i>
		</a>
	</div>
	<div style="width:33.3333%;display:inline-block;text-align:right;padding-right:15px;">
		<% if request.path == "/" + current_user.username || request.path == "/" + current_user.username + "/doing" || request.path == "/" + current_user.username + "/want" %>
			<span onclick="scrollGO()" style="position:relative;display:inline-block;vertical-align:middle;width:50px;height:50px;line-height:50px;background:rgba(25,25,25,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
				<i>
					<%= image_tag "up_FAFAFA.svg", :style =>'width:16px;height:16px;opacity:0.8;' %>
				</i>
			</span>
		<% else %>
			<a href="/<%= current_user.username %>" style="position:relative;display:inline-block;vertical-align:middle;width:50px;height:50px;line-height:50px;background:rgba(25,25,25,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
				<i>
					<%= image_tag "avatar_FAFAFA.svg", :style =>'width:16px;height:16px;opacity:0.8;' %>
				</i>
			</a>
		<% end %>
	</div>
</div>

<%#TOPに戻る%>
<script defer>
	function scrollGO(){
  		// ページ上部までスムーズにスクロール
	    $('html,body').animate({
	        scrollTop: 0,
	    }, 250, 'swing');
	}
</script>

<%#投稿モーダル%>
<div class="modal bottom fade" id="myModal_post">
    <div class="modal-dialog">
      <div class="a1">
        <div class="a14">
          <div class="d1">
            <div class="d2" style="background:rgba(12,12,12,1);"></div>
          </div>
        </div>
        <div class="a8" style="text-align:center;">   	
	  		<div style="font-size:28px;font-weight:bold;">
				Create Post
			</div>
			<div style="font-size:14px;opacity:0.8;">
				投稿を作成
			</div>
	        <div style="height:30px;"></div>
	        <div style="padding:0 6%;">
	      		<div class="inline_block_top" style="width:33.33%;text-align:center;">
	      			<%= link_to(works_movie_path) do %>
				      	<div style="position:relative;display:inline-block;vertical-align:middle;width:68px;height:68px;line-height:68px;border-radius:50%;color:rgba(250,250,250,0.9);background:rgba(40,40,40,0.5);border:solid 1px rgba(40,40,40,0.1);box-shadow:0px 2px 15px rgba(0,0,0,0.3);">
					      	<i>
					        	<%= image_tag "movie_FAFAFA.svg", :style =>'width:24px;height:24px;' %>
					        </i>
				        </div>	
				        <div style="height:15px;"></div>
				        <div style="font-size:11px;color:#FAFAFA;">
					        映画/テレビ
					    </div>	
				    <% end %>	
			    </div>
	        	<div class="inline_block_top" style="width:33.33%;text-align:center;">        		
	        		<%= link_to(works_book_path) do %>
				      	<div style="position:relative;display:inline-block;vertical-align:middle;width:68px;height:68px;line-height:68px;border-radius:50%;color:rgba(250,250,250,0.9);background:rgba(40,40,40,0.5);border:solid 1px rgba(40,40,40,0.1);box-shadow:0px 2px 15px rgba(0,0,0,0.3);">
					      	<i>
					        	<%= image_tag "book_FAFAFA.svg", :style =>'width:24px;height:24px;' %>
					        </i>
				        </div>	
				        <div style="height:15px;"></div>
				        <div style="font-size:11px;color:#FAFAFA;">
					        ブック/コミック
					    </div>	
				    <% end %>
			    </div>
	        	<div class="inline_block_top" style="width:33.33%;text-align:center;">
	        		<%= link_to(works_music_path) do %>
				      	<div style="position:relative;display:inline-block;vertical-align:middle;width:68px;height:68px;line-height:68px;border-radius:50%;color:rgba(250,250,250,0.9);background:rgba(40,40,40,0.5);border:solid 1px rgba(40,40,40,0.1);box-shadow:0px 2px 15px rgba(0,0,0,0.3);">
					      	<i>
					        	<%= image_tag "music_FAFAFA.svg", :style =>'width:24px;height:24px;' %>
					        </i>
				        </div>	
				        <div style="height:15px;"></div>
				        <div style="font-size:11px;color:#FAFAFA;">
					        ミュージック
					    </div>
				    <% end %>	
			    </div>
		    </div>
	        <div style="height:100px;"></div>
        </div>
        <div style="position:fixed;bottom:5%;left:0%;width:100%;z-index:99;">
        	<div style="width:100%;display:inline-block;text-align:center;">				
				<span data-dismiss="modal" id="dismiss_post" style="position:relative;display:inline-block;vertical-align:middle;width:60px;height:60px;line-height:60px;background:rgba(0,60,85,1);text-align:center;border-radius:50%;box-shadow:0px 0px 15px rgba(0,0,0,0.3);">
					<i>
						<%= image_tag "plus_FAFAFA.svg", :style =>'width:22px;height:22px;transform-origin:50%,50%;transform:rotate(45deg);' %>
					</i>
				</span>				
			</div>
		</div>
      </div>
    </div>
  </div>
</div>
<%#モーダルtubolinks不具合修正%>
<script defer>
  $(function(){
    var display_post = $('#myModal_post').css('display');
    //モーダルが表示されているのに表示判定されてなかったら
    if(display_post === 'block'){
      //モーダルを表示状態にする
      $('body').removeClass('modal-open');
      $('.modal-backdrop').remove();
      $('#myModal_post').modal('toggle');
      //クリックでモーダルを閉じる 
      $('#dismiss_post').on("click",function(){
        $('body').removeClass('modal-open');
        $('.modal-backdrop').remove();
        $('#myModal_post').modal('hide'); 
      });
    }       
  });
</script>

app/views/partial/_post_modal.html.erb
<%#投稿ボタン%>
<div class="btns_plus">
	<a href="" data-toggle="modal" data-target="#myModal_post" id="btn_plus">
		<i><%= image_tag "plus_white.png", :class =>'img_plus' %></i>
	</a>
</div>	

<%#投稿モーダル%>
<div class="modal fade" id="myModal_post">
    <div class="modal-dialog">
      <div class="a1">
        <div class="a4">
          <div class="d1">
            <div class="d6"></div>
          </div>
        </div>
        <div class="a8" style="text-align:center;"> 
        	<div class="">	
		  		<div style="font-size:24px;color:#FAFAFA;margin:0px 0px 40px;">
			      	投稿を作成
		        </div>
		  		<div class="btns_choice02">
		  			<div>
				      	<%= link_to(works_movie_path) do %>
					      	<div class="btn_icon">
					      		<span>
					        		<%= image_tag "movie_white.png", :style =>'width:30px;height:30px;' %>
					        	</span>
					        </div>
				        <% end %>
			        </div>
			        <div style="font-size:12px;color:#FAFAFA;margin-top:10px;">
			        	映画/テレビ
			        </div>
		        </div>
		        <div class="btns_choice01">
		        	<div>
		        		<%= link_to(works_book_path) do %>
				        	<div class="btn_icon">
					      		<span>
					        		<%= image_tag "book_white.png", :style =>'width:30px;height:30px;' %>
					        	</span>
					        </div>
				        <% end %>
				    </div>
			        <div style="font-size:12px;color:#FAFAFA;margin-top:10px;">
			        	ブック
			        </div>
		        </div>
		        <div class="btns_choice02">
		        	<div>
				      	<%= link_to(works_music_path) do %>
				        	<div class="btn_icon">
					      		<span>
					        		<%= image_tag "music_white.png", :style =>'width:30px;height:30px;' %>
					        	</span>
					        </div>
				        <% end %>
			        </div>
			        <div style="font-size:12px;color:#FAFAFA;margin-top:10px;">
			        	ミュージック
			        </div>
		        </div> 
	        </div>   
        </div>
        <a class="btns_plus" data-dismiss="modal" id="dismiss_post">
			<span id="btn_plus">
				<i><%= image_tag "plus_white.png", :class =>'img_time' %></i>
			</span>
		</a>
      </div>
    </div>
  </div>
</div>

<%#モーダルtubolinks不具合修正%>
<script type="text/javascript">
  $(function(){
    var display_post = $('#myModal_post').css('display');
    //モーダルが表示されているのに表示判定されてなかったら
    if(display_post === 'block'){
      //モーダルを表示状態にする
      $('body').removeClass('modal-open');
      $('.modal-backdrop').remove();
      $('#myModal_post').modal('toggle');
      //クリックでモーダルを閉じる 
      $('#dismiss_post').on("click",function(){
        $('body').removeClass('modal-open');
        $('.modal-backdrop').remove();
        $('#myModal_post').modal('hide'); 
      });
    }       
  });
</script>