config/routes.rb
Rails.application.routes.draw do

  root :to => 'works#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get ":id" => "users#posts"
  get 'users/user' => "users#user"
  get 'users/ajax_user_list' => "users#ajax_user_list"
  get ':id/following' => "users#following"
  get ':id/ajax_following_list' => "users#ajax_following_list"
  get ':id/follower' => "users#follower"
  get ':id/ajax_follower_list' => "users#ajax_follower_list"
  get 'users/configuration' => "users#configuration"
  get 'users/policy' => "users#policy"
  get 'users/terms' => "users#terms"
  get 'users/contact' => "users#contact"
  get 'users/notifications' => "users#notifications"
  get 'users/ajax_validate_username' => "users#ajax_validate_username"
  get 'users/follow_request' => "users#follow_request"

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
     get :requesting, :requesters
    end
  end
  resources :follow_requests,       only: [:create, :destroy]

  post "follow_requests/:id/approval" => "follow_requests#approval"
  post "follow_requests/:id/unapproval" => "follow_requests#unapproval"

  get "post/:id" => "works#post"
  get 'works/movie' => "works#movie"
  get 'works/ajax_movie_list' => "works#ajax_movie_list"
  get 'works/book' => "works#book"
  get 'works/ajax_book_list' => "works#ajax_book_list"
  get 'works/music' => "works#music"
  get 'works/ajax_music_list' => "works#ajax_music_list"
  get 'works/new' => "works#new"
  get "works/:id/edit" => "works#edit"
  get "works/:id/copy" => "works#copy"
  post 'works/save' => "works#save"
  post "works/:id/update" => "works#update"
  post "works/:id/destroy" => "works#destroy"

  get 'memos/:post_id/new' => "memos#new"
  post "memos/create" => "memos#create"
  get 'memos/:id/edit' => "memos#edit"
  post "memos/:id/update" => "memos#update"
  post "memos/:id/destroy" => "memos#destroy"

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :invitations, only: [:create, :destroy]
  get 'invitation/:id' => "invitations#invitation"
  get 'invite' => "invitations#invite"

  get 'lists/setting/profile' => "lists#profile"
  post ":id/create_profile_sync" => "lists#create_profile_sync"
  post ":id/create_profile" => "lists#create_profile"
  post ":id/destroy_profile" => "lists#destroy_profile"
  post ":id/create_favorite" => "lists#create_favorite"
  post ":id/destroy_favorite" => "lists#destroy_favorite"

  get 'works/test' => "works#test"


  get '*path', to: 'application#render_404'
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :invited_user, class_name: 'User', optional: true 
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def invite  
    @invitation = Invitation.new  

    @invitations = Invitation.where(user_id: current_user.id).order(created_at: "DESC")
    @invitations_true = @invitations.where(used: true)
  end

  def invitation
  	@invitation = Invitation.find_by(code: params[:id], used: false)
  end

  def create
  	loop do
      @code = SecureRandom.hex(6)
      break unless Invitation.where(code: @code).exists?
    end
    @invitation = Invitation.new(user_id: current_user.id, code: @code)
    if @invitation.save
    	redirect_back(fallback_location: root_path)
    else
    	redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    
  end
  
end

app/views/invitations/invitation.html.erb
<div class="main">
	<div class="block_side">
	</div>
	<div class="block_main">		
		<div class="a1">
	        <div class="a4">
	          <div class="d1">
	          	<div class="d6"></div>
	          </div>
	        </div>
	        <div class="a8" style="text-align:center;">
	        	<div style="height:50px;"></div>
		        <div class="invitation_card02">
					<span>	
						<% if user_signed_in? %>
							<div>
				            	<%= image_tag "tavore_logo_01.png", :style =>'width:100px;height:100px;' %>
				            </div>
				            <div style="font-size:22px;">
				                Not Found
				            </div>
				            <div style="height:3vh;"></div>
				            <div class="font_white_min">
			              		ログインしているユーザーは
			              		<br>ご利用頂けないページです
			              	</div>
			              	<div style="height:5vh;"></div>					     
						<% else %>
							<% if @invitation.present? %>
				              	<%= image_tag @invitation.user.image(:large), :class => "img_user13" %>
				              	<div style="height:1vh;"></div>
				              	<div class="font_white_max">
				              		<%= @invitation.user.name %>
				              	</div>
				              	<div style="height:4vh;"></div>		              	
					            <div class="font_white">
						            TAVORE with me!
					            </div>					
				              	<div style="height:2vh;"></div>
				              	<div class="font_white_min">
				              		<%= @invitation.user.name %>があなたを招待しています
				              	</div>
				              	<div style="height:5vh;"></div>
				              	<a href="" data-toggle="modal" data-target="#myModal_sign_up">
							        <div class="btn_register">
										アカウントを作成
									</div>
						      	</a>	
						      	<div style="height:5vh;"></div>
						    <% else %>
						    	<div>
					            	<%= image_tag "tavore_logo_01.png", :style =>'width:100px;height:100px;' %>
					            </div>
					            <div style="font-size:22px;">
					                Not Found
					            </div>
					            <div style="height:3vh;"></div>
					            <div class="font_white_min">
				              		この招待コードは存在しないか
				              		<br>すでに使用されています
				              	</div>				              	
				              	<div style="height:5vh;"></div>
						    <% end %>
						<% end %>
				    </span>
			    </div>
	        </div>
		</div>		
	</div>
	<div class="block_side">
	</div>
</div>


<% unless user_signed_in? %>
	<% if @invitation.present? %>
		<%#サインアップモーダル%>
		<div class="modal bottom fade" id="myModal_sign_up">
		  <div class="height_modal"></div>
		    <div class="modal-dialog">
		      <div class="a1">
		        <div class="a4">
		          <div class="d1">
		            <div class="d6"></div>
		          </div>
		        </div>
		        <div class="a7">
		            <a href="" data-toggle="modal" data-dismiss="modal">
		              <div style="padding:20px;">
		                <%= image_tag "cross_777777.svg", :style =>'width:18px;height:18px;opacity:0.5;' %>
		              </div>
		            </a>  
		        </div>
		        <div class="a8" style="text-align:center;">  
		        	<div style="height:7vh;"></div>          	
					<div class="font_white_big">
						Sign up
					</div>
					<div class="gogo">
						<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
						  <%= hidden_field_tag :invitation_id, @invitation.id %>
						  <%= f.text_field :name,placeholder: "name", required: "", autofocus: true %>
						  <%= f.email_field :email,placeholder: "email", required: "" %>
						  <%= f.password_field :password,placeholder: "password", required: "" %>
						  <%= f.password_field :password_confirmation,:placeholder => 'password confirmation', required: "" %>
						  <div style="height:2vh;"></div>
		      			  <%= f.submit "完了",class:"btn_session" %>
						<% end %>
					</div>
					<div style="height:7vh;"></div>
					<div class="font_gray_min" style="padding:0 15%;text-align:left;">
						アカウントを作成することで,TAVOREの
						<%= link_to terms_path do %>
							利用規約
						<% end %>
						と
						<%= link_to policy_path do %>
							プライバシーポリシー
						<% end %>
						に同意されたものとします。
					</div>					
		        </div>
		      </div>
		    </div>
		  </div>
		</div>
	<% end %>
<% end %>

app/views/invitations/invite.html.erb
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.8/clipboard.min.js"></script>

<div class="bar_post">			
	<div style="">
		<div class="inline_block_middle" style="width:15%;">
			<div style="text-align:left;padding-left:10px;">
				<a href="javascript:void(0);" onclick="window.history.back();">
		        	<%= image_tag "left_C2C2C2.svg", :style =>'width:15px;height:15px;' %>
		        </a>										
			</div>
		</div>
		<div class="inline_block_middle" style="width:70%;">
			<div class="contain_title02" style="text-align:center;">
				<div style="font-size:14px;color:#c2c2c2;">
					友達を招待
				</div>
			</div>
		</div>
		<div class="inline_block_middle" style="width:15%;">
			<div style="text-align:right;">							
			</div>
		</div>
	</div>
</div>

<div class="main">
	<div class="block_side">
	</div>
	<div class="block_main">
		<div class="a1">
          <div class="a4">
            <div class="d1">    
           	  <%= image_tag "invitation.jpg", :class =>'img_myboom_blur' %>
              <div class="d3"></div>
            </div>
          </div>
          <div class="a6">
          		<div style="height:50px;"></div>
          		<div style="height:40px;"></div>
          		<div style="height:5vh;"></div>
          		<div class="font_white_big" style="padding-left:15px;">
          			How to invite
          		</div>
          		<div style="height:1vh;"></div>
          		<div class="font_white_min" style="padding-left:15px;padding-right:15px;color:#b4b4b4">
          			招待URLを発行して教えてあげることで
          			<br>あなたの友達はTAVOREを始めることができます
          		</div>
          		<div style="height:5vh;"></div>
          		<div class="font_white_big" style="padding-left:15px;">
          			Invitation code
          		</div>
          		<div style="height:1vh;"></div>
          		<div class="font_white_min" style="padding-left:15px;padding-right:15px;color:#b4b4b4">
          			招待URLコード
          		</div>
          		<div style="height:3vh;"></div>
          		<div class="horizontal_scroll">	
          			<div class="scroll_item01">	
          				<%= form_for @invitation do |f| %> 
							<button type="submit" data-confirm="招待URLを発行しますか？" style="width:100%;height:100%;">
							  	<div class="card01" style="background:rgba(220,220,220,0.15);">
							  		<span>
									  	<%= image_tag "add_FAFAFA.svg", :style =>'width:40px;height:40px;opacity:0.7;' %>
									  	<div style="font-size:10px;color:#FAFAFA;opacity:0.7;margin-top:15px;">
									  		招待URLを発行する
									  	</div>		
								  	</span>	
						  		</div>	 
					  		</button>							 
						<% end %>
					</div>
					<% if @invitations.present? %>
						<% @invitations.each.with_index(1) do |invitation, i| %>
							<% if invitation.used == true %>
								<div class="scroll_item01">				
								  	<div class="card01">
								  		<span>
										  	<%= image_tag "user.svg", :style =>'width:45px;height:45px;border-radius:50%;background:rgba(0,0,0,0.1);object-fit:cover;' %>
										  	<div style="height:10px;"></div>
										  	<div style="font-size:10px;color:#999999;">
										  		<div class="font_white_min" style="opacity:0.9;">
													<%= invitation.code %>
												</div>
												<div style="height:10px;"></div>
						          				<div class="font_white_min" style="color:#FB473E;">
													alredy used
												</div>
										  	</div>		
									  	</span>	
								  	</div>	  	
								</div>
							<% else %>
								<div class="scroll_item01">				
								  	<div class="card01">
								  		<a href="" data-clipboard-text="https://www.tavore.net/invitation/<%= invitation.code %>" id="copy<%= invitation.id %>" style="width:100%;height:100%;">
									  		<span>
											  	<%= image_tag "user.svg", :style =>'width:45px;height:45px;border-radius:50%;background:rgba(0,0,0,0.1);object-fit:cover;' %>
											  	<div style="height:10px;"></div>
											  	<div style="font-size:10px;color:#999999;">
											  		<div class="font_white_min" style="opacity:0.9;">
														<%= invitation.code %>
													</div>
													<div style="height:10px;"></div>
							          				<div class="font_white_min" style="color:#38ef7d;">
														タップでURLをコピー
													</div> 
											  	</div>		
										  	</span>	
									  	</a>  	
								  	</div>
								</div>
								<%#コピーのJS%>
								<script defer>
									$(function(){
									  var clipboard = new Clipboard('#copy<%= invitation.id %>');
									  clipboard.on('success', function(e) {
									    console.info('Trigger:', e.trigger);
									    alert('コピーできました');
									  });
									  clipboard.on('error', function(e) {
									    console.error('Trigger:', e.trigger);
									    alert('このブラウザでは対応していません');
									  });
								  	});
								</script>	  
							<% end %>
						<% end %>
					<% end %>
				</div>
				<div style="height:5vh;"></div>
          		<div class="font_white_big" style="padding-left:15px;">
          			User you invited
          		</div>
          		<div style="height:1vh;"></div>
          		<div class="font_white_min" style="padding-left:15px;padding-right:15px;color:#b4b4b4">
          			あなたが招待したユーザー
          		</div>
          		<% if @invitations.present? %>
          			<div style="height:3vh;"></div>	
          			<div class="horizontal_scroll">
	          			<% @invitations_true.each.with_index(1) do |invitation, i| %>
		          			<% if User.find_by(id: invitation.invited_user) %>	
			          			<div class="scroll_item03">	
			          				<a href="" data-toggle="modal" data-target="#myModal_profile_<%= invitation.invited_user.id %>">
				          				<%= image_tag invitation.invited_user.image(:medium), :style => "width:55px;height:55px;border-radius:50%;background:rgba(0,0,0,0.1);object-fit: cover;" %>
				          				<div style="height:10px;"></div>	
				          				<div class="font_white_min">
				          					<%= invitation.invited_user.name %>
				          				</div>
				          			</a>
			          			</div>
		          			<% end %>
	          			<% end %>
	          		</div>
	          	<% else %>
	          		<div style="height:1vh;"></div>	
          			<div class="font_white_min" style="padding-left:15px;color:#b4b4b4;">
	          			- 招待したユーザーはいません -
	          		</div>
	          	<% end %>
			  	<div style="height:5vh;"></div>	
		  </div>
        </div>	
	</div>
	<div class="block_side">
	</div>
</div>

<% if @invitations.present? %>
	<% @user_list = [] %>
	<% @invitations.each.with_index(1) do |invitation, i| %>
		<% if invitation.used == true %>
			<% if User.find_by(id: invitation.invited_user) %>
				<% unless @user_list.include?(invitation.invited_user.id) %>
					<% @user = invitation.invited_user %>
			  		<% @checkeds_i = Post.where(user_id: @user.id).where.not(review: "bookmark").size %>
			  		<% @bookmarks_i = Post.where(user_id: @user.id, review: "bookmark").size %>
					<%= render partial: 'partial/profile', locals: { user: @user, checkeds_i: @checkeds_i, bookmarks_i: @bookmarks_i } %>
					<% @user_list.push(invitation.invited_user.id) %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>