config/routes.rb
Rails.application.routes.draw do

  root :to => 'works#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get ":id" => "users#posts"
  get 'users/user' => "users#user"
  get 'users/ajax_user_list' => "users#ajax_user_list"
  get ':id/following' => "users#following"
  get ':id/ajax_following_list' => "users#ajax_following_list"
  get ':id/follower' => "users#follower"
  get ':id/ajax_follower_list' => "users#ajax_follower_list"
  get 'users/configuration' => "users#configuration"
  get 'users/policy' => "users#policy"
  get 'users/terms' => "users#terms"
  get 'users/contact' => "users#contact"
  get 'users/notifications' => "users#notifications"
  get 'users/ajax_validate_username' => "users#ajax_validate_username"
  get 'users/follow_request' => "users#follow_request"

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
     get :requesting, :requesters
    end
  end
  resources :follow_requests,       only: [:create, :destroy]

  post "follow_requests/:id/approval" => "follow_requests#approval"
  post "follow_requests/:id/unapproval" => "follow_requests#unapproval"

  get "post/:id" => "works#post"
  get 'works/movie' => "works#movie"
  get 'works/ajax_movie_list' => "works#ajax_movie_list"
  get 'works/book' => "works#book"
  get 'works/ajax_book_list' => "works#ajax_book_list"
  get 'works/music' => "works#music"
  get 'works/ajax_music_list' => "works#ajax_music_list"
  get 'works/new' => "works#new"
  get "works/:id/edit" => "works#edit"
  get "works/:id/copy" => "works#copy"
  post 'works/save' => "works#save"
  post "works/:id/update" => "works#update"
  post "works/:id/destroy" => "works#destroy"

  get 'memos/:post_id/new' => "memos#new"
  post "memos/create" => "memos#create"
  get 'memos/:id/edit' => "memos#edit"
  post "memos/:id/update" => "memos#update"
  post "memos/:id/destroy" => "memos#destroy"

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :invitations, only: [:create, :destroy]
  get 'invitation/:id' => "invitations#invitation"
  get 'invite' => "invitations#invite"

  get 'lists/setting/profile' => "lists#profile"
  post ":id/create_profile_sync" => "lists#create_profile_sync"
  post ":id/create_profile" => "lists#create_profile"
  post ":id/destroy_profile" => "lists#destroy_profile"
  post ":id/create_favorite" => "lists#create_favorite"
  post ":id/destroy_favorite" => "lists#destroy_favorite"

  get 'works/test' => "works#test"


  get '*path', to: 'application#render_404'
end

app/models/memo.rb
class Memo < ApplicationRecord
	validates :content, presence: true

  	belongs_to :user
  	belongs_to :post
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def new
  	@post = Post.find(params[:post_id])
  end

  def create
  	@post = Post.find(params[:post_id])
  	if @memo = Memo.create(user_id: current_user.id, post_id: @post.id, content: params[:content])
    	redirect_to "/post/#{@post.id}"
    else
    	redirect_to "/post/#{@post.id}"
    end   
  end

  def edit
  	@memo = Memo.find(params[:id])
    if !(current_user == @memo.user)
      redirect_to root_path
    end
  end

  def update
  	@memo = Memo.find(params[:id])
  	@post = Post.find(@memo.post.id)
  	if params[:content]
  		@memo.content = params[:content]
  	end
  	if @memo.save
      redirect_to "/post/#{@post.id}"
    else
      redirect_to "/post/#{@post.id}"
    end   
  end

  def destroy
  	@memo = Memo.find(params[:id])
  	@post = Post.find(@memo.post.id)
    if @memo.destroy
      redirect_to "/post/#{@post.id}"
    else
      redirect_to "/post/#{@post.id}"
    end   
  end

end

app/views/memos/edit.html.erb
<%#トップバー%>
<div class="bar_top">      
    <div class="inline_block_middle" style="width:20%;">
    	<div style="text-align:left;padding-left:15px;">
        	<a href="javascript:void(0);" onclick="window.history.back();">
          		<%= image_tag "left_FAFAFA.svg", :style =>'width:18px;height:18px;' %>
        	</a>                    
      	</div>
    </div>
    <div class="inline_block_middle" style="width:60%;">
      	<div class="line_limit01" style="text-align:center;">
        	<div style="font-size:14px;color:#FAFAFA;">
          		メモを編集
        	</div>
      	</div>
    </div>
    <div class="inline_block_middle" style="width:20%;">
    	<div style="text-align:right;padding-right:15px;">
    		<button id="btn_post" style="font-size:15px;color:#2FB4B4;">
				更新
			</button>
	    </div>
    </div>
</div>
<div style="height:50px;"></div>

<%= form_tag("/memos/#{@memo.id}/update", method: :post, :name => "myform", :style => "height:calc(100% - 50px);") do %>
	<%#バリデーション用submit%>
	<input type="submit" style="display:none" name="submit">
	<%#内容%>
	<div class="form05" style="text-align:center;width:90%;height:100%;margin:0 auto;">
		<textarea name="content" id="textarea" placeholder="メモを書く(非公開)" wrap="soft" required="required" autofocus="autofocus"><%= @memo.content %></textarea>
	</div>
<% end %>

<%#投稿ボタンボタン%>
<script defer>
	$('#btn_post').click(function() {
		$("input[name=submit]").click();
	});
</script>

app/views/memos/new.html.erb
<%#トップバー%>
<div class="bar_top">      
    <div class="inline_block_middle" style="width:20%;">
    	<div style="text-align:left;padding-left:15px;">
        	<a href="javascript:void(0);" onclick="window.history.back();">
          		<%= image_tag "left_FAFAFA.svg", :style =>'width:18px;height:18px;' %>
        	</a>                    
      	</div>
    </div>
    <div class="inline_block_middle" style="width:60%;">
      	<div class="line_limit01" style="text-align:center;">
        	<div style="font-size:14px;color:#FAFAFA;">
          		メモを作成
        	</div>
      	</div>
    </div>
    <div class="inline_block_middle" style="width:20%;">
    	<div style="text-align:right;padding-right:15px;">
    		<button id="btn_post" style="font-size:15px;color:#2FB4B4;">
				投稿
			</button>
	    </div>
    </div>
</div>
<div style="height:50px;"></div>

<%= form_tag(memos_create_path, method: :post, :name => "myform", :style => "height:calc(100% - 50px);") do %>
	<%#バリデーション用submit%>
	<input type="submit" style="display:none" name="submit">
	<%= hidden_field_tag :post_id, @post.id %>
	<%#内容%>
	<div class="form05" style="text-align:center;width:90%;height:100%;margin:0 auto;">
		<textarea name="content" id="textarea" placeholder="メモを書く(非公開)" wrap="soft" required="required" autofocus="autofocus"></textarea>
	</div>
<% end %>

<%#投稿ボタンボタン%>
<script defer>
	$('#btn_post').click(function() {
		$("input[name=submit]").click();
	});
</script>